schema_version = "1.0.0"

id = "io_br2proj"
name = "Br2Proj"
version = "1.0.0"
tagline = "The extension adds support for Bloodrayne 2 game file formats"
maintainer = "PavelSharp"
type = "add-on"

tags = ["Import-Export", "Mesh", "Material", "Animation"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

website = "https://github.com/PavelSharp/br2proj"

copyright = ["2025 PavelSharp"]

[permissions]
files = "Import/export Bloodrayne 2 files from/to disk"



# Optional: bundle 3rd party Python modules.
# https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
# wheels = [
#   "./wheels/hexdump-3.3-py3-none-any.whl",
#   "./wheels/jsmin-3.0.1-py3-none-any.whl",
# ]

# Optional: build settings.
# https://docs.blender.org/manual/en/dev/advanced/extensions/command_line_arguments.html#command-line-args-extension-build
# [build]
# paths_exclude_pattern = [
#   "__pycache__/",
#   "/.git/",
#   "/*.zip",
# ]